train_data: /data/ydc_data/urban_target_detection_train_add_neg.h5
cv_data: /data/ydc_data/urban_target_detection_validate_add_neg.h5
test_data: /data/ydc_data/urban_target_detection_test_add_neg.h5
spk_emb_file_path: /home/ydc/wsed/target_sound_detection/data/features/mel_path.h5
encoder_path: /home/ydc/wsed/target_sound_detection/src/cnn_best_model_at_epoch_45.pth.tar
CDur_path: /home/ydc/wsed/target_sound_detection/experiments/CDur_fusion/2021-09-06_21-21-09_643f910e0f1511eca57f615e6b17f09b/run_model_17_loss=-0.2995.pt
batch_size: 64
num_workers: 3
data_args:
    mode: stratified # Stratified split to train and cv
optimizer: AdamW
label: /home/ydc/wsed/target_sound_detection/data/flists/strong_test_add_neg.tsv
lr_: 0.00005
optimizer_args:
    lr: 0.0001
epochs: 100 
model: Join_fusion
model_args: #Currently None, no additional args
    temppool: linear
outputpath: experiments/UrbanSED
transforms: [freqmask, timemask, shift]
shuffle: False
sampler: MinimumOccupancySampler
loss_sed: BCELoss
loss_ce: CELoss
save: one
early_stop: 7
scheduler_args:
    patience: 3
    factor: 0.1
outputpath: experiments
scale: 2
postprocessing: median
pre_train: True
